[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#800000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF5F5"
textColor = "#1E293B"
font = "sans serif"
